BASE_URL = 'https://naturezway.com'
COLLECTIONS = [
  'bath-tissue',
  'paper-towels',
  'plates-bowels',
  'cutlery',
  'napkins',
  'hot-and-cold-cups',
  'cold-cups',
  'straws',
  'to-go-containers',
  'food-cling-wrap',
  'sponges-and-cleaning-cloths'
]

TIMEOUT = 10
MIN_TIMEOUT = 10
MAX_TIMEOUT = 25

MIN_COLLECTION_SLEEP = 5
MAX_COLLECTION_SLEEP = 10

MIN_PRODUCT_SLEEP = 10
MAX_PRODUCT_SLEEP = 25

HEADERS = [
    'uniqueIdentifier',
    'URL',
    'availableForSale',
    'title',
    'description',
    'metaTitle',
    'metaDescription',
    'vendor',
    'manufacturerName',
    'brand',
    'model',
    'price',
    'vendorCategory.0',
    'vendorCategory.1',
    'categories.0',
    'categories.1',
    'material',
    'color',
    'approvedBy',
    'totalInventory',
    'images.0',
    'images.1',
    'images.2',
    'images.3',
    'images.4',
    'images.5',
    'images.6',
    'manufacturerNumber',
    'upc',
    'sku',
    'specs.0.name','specs.0.value',
    'specs.1.name','specs.1.value',
    'specs.2.name','specs.2.value',
    'specs.3.name','specs.3.value',
    'specs.4.name','specs.4.value',
    'specs.5.name','specs.5.value',
    'specs.6.name','specs.6.value',
    'specs.7.name','specs.7.value',
    'specs.8.name','specs.8.value',
    'specs.9.name','specs.9.value',
    'specs.10.name','specs.10.value',
    'specs.11.name','specs.11.value',
    'specs.12.name','specs.12.value',
    'option.0.name','option.0.value',
    'option.1.name','option.1.value',
    'option.2.name','option.2.value',
    'option.3.name','option.3.value',
    'option.4.name','option.4.value',
    'option.5.name','option.5.value',
    'option.6.name','option.6.value',
    'option.7.name','option.7.value',
    'option.8.name','option.8.value',
    'option.9.name','option.9.value',
    'option.10.name','option.10.value',
    'option.11.name','option.11.value',
    'option.12.name','option.12.value',
    'productMinOrderCases',
    'productMinOrderPrice',
    'caseSize',
    'packSize',
    'productLength',
    'productWidth',
    'productHeight',
    'productWeight',
    'packageLength',
    'packageWidth',
    'packageHeight',
    'packageWeight',
    'shippingFrom',
    'shippingCost',
    'freeShipping',
    'certificationsAndStandards',
    'origin',
    'productValue.0',
    'productValue.1',
    'canCustomize',
    'ourCost',
    'despensingType',
    'packagingType',
    'productForm',
    'scent',
    'volumeML',
    'volumeOZ',
    'border',
    'design',
    'shape',
    'towelType',
    'weightGSM',
    'feerPerRoll',
    'numberOfRolls',
    'numerOfSheets',
    'ply',
    'fit',
    'pattern',
    'threadCount',
    'pocketDepth',
    'ingredients',
    'itemForm',
    'microwaveSafe',
    'thickness',
]

MODEL_KEYWORDS = [
  '2-Ply',
  '2 Ply',
  'Disposable',
  'Reusable',
  'Biodegradable',
  'Compostable',
  'Recyclable',
  'Ultra Absorbent',
  'Round',
  'Square',
  'Oval',
  'Dinner',
  'Everyday',
  'Cocktail',
  'Double Layered',
  'Ripple Double Sleeved',
  'Frosted',
  'Black',
  'Flat',
  'Jumbo',
  'Flexible',
  'Giant',
  'Clear',
  'Sushi',
  'Rectangle',
]

SIZE_FORMATS_EXAMPLES = [
  "6\"",
  "6\" inch",
  "6\" inches",
  "6\" INCH",
  "6\" INCHES",
  "7\" Inch",
  "7\" Inches",

  "6.5\"",
  "6.5\" inch",
  "6.5\" inches",
  "6.5\" INCH",
  "6.5\" INCHES",
  "7.5\" Inch",
  "7.5\" Inches",

  "7\" x 10\" inch",
  "7\" x 10\" inches",
  "7\" x 10\" INCH",
  "7\" x 10\" INCHES",
  "7\" x 10\" Inch",
  "7\" x 10\" Inches",
  "7\" X 10\" inch",
  "7\" X 10\" inches",
  "7\" X 10\" INCH",
  "7\" X 10\" INCHES",
  "7\" X 10\" Inch",
  "7\" X 10\" Inches",
  "7\" x 10\"",
  "7\" X 10\"",

  "7.5\" x 10.5\" inch",
  "7.5\" x 10.5\" inches",
  "7.5\" x 10.5\" INCH",
  "7.5\" x 10.5\" INCHES",
  "7.5\" x 10.5\" Inch",
  "7.5\" x 10.5\" Inches",
  "7.5\" X 10.5\" inch",
  "7.5\" X 10.5\" inches",
  "7.5\" X 10.5\" INCH",
  "7.5\" X 10.5\" INCHES",
  "7.5\" X 10.5\" Inch",
  "7.5\" X 10.5\" Inches",
  "7.5\" x 10.5\"",
  "7.5\" X 10.5\"",

  "7\" x 10.5\" inch",
  "7\" x 10.5\" inches",
  "7\" x 10.5\" INCH",
  "7\" x 10.5\" INCHES",
  "7\" x 10.5\" Inch",
  "7\" x 10.5\" Inches",
  "7\" X 10.5\" inch",
  "7\" X 10.5\" inches",
  "7\" X 10.5\" INCH",
  "7\" X 10.5\" INCHES",
  "7\" X 10.5\" Inch",
  "7\" X 10.5\" Inches",
  "7\" x 10.5\"",
  "7\" X 10.5\"",

  "7.5\" x 10\" inch",
  "7.5\" x 10\" inches",
  "7.5\" x 10\" INCH",
  "7.5\" x 10\" INCHES",
  "7.5\" x 10\" Inch",
  "7.5\" x 10\" Inches",
  "7.5\" X 10\" inch",
  "7.5\" X 10\" inches",
  "7.5\" X 10\" INCH",
  "7.5\" X 10\" INCHES",
  "7.5\" X 10\" Inch",
  "7.5\" X 10.5\" Inches",
  "7.5\" x 10\"",
  "7.5\" X 10\"",

  "7\"x 10\" inch",
  "7\"x 10\" inches",
  "7\"x 10\" INCH",
  "7\"x 10\" INCHES",
  "7\"x 10\" Inch",
  "7\"x 10\" Inches",
  "7\"X 10\" inch",
  "7\"X 10\" inches",
  "7\"X 10\" INCH",
  "7\"X 10\" INCHES",
  "7\"X 10\" Inch",
  "7\"X 10\" Inches",
  "7\"x 10\"",
  "7\"X 10\"",

  "7.5\"x 10.5\" inch",
  "7.5\"x 10.5\" inches",
  "7.5\"x 10.5\" INCH",
  "7.5\"x 10.5\" INCHES",
  "7.5\"x 10.5\" Inch",
  "7.5\"x 10.5\" Inches",
  "7.5\"X 10.5\" inch",
  "7.5\"X 10.5\" inches",
  "7.5\"X 10.5\" INCH",
  "7.5\"X 10.5\" INCHES",
  "7.5\"X 10.5\" Inch",
  "7.5\"X 10.5\" Inches",
  "7.5\"x 10.5\"",
  "7.5\"X 10.5\"",

  "7\"x 10.5\" inch",
  "7\"x 10.5\" inches",
  "7\"x 10.5\" INCH",
  "7\"x 10.5\" INCHES",
  "7\"x 10.5\" Inch",
  "7\"x 10.5\" Inches",
  "7\"X 10.5\" inch",
  "7\"X 10.5\" inches",
  "7\"X 10.5\" INCH",
  "7\"X 10.5\" INCHES",
  "7\"X 10.5\" Inch",
  "7\"X 10.5\" Inches",
  "7\"x 10.5\"",
  "7\"X 10.5\"",

  "7.5\"x 10\" inch",
  "7.5\"x 10\" inches",
  "7.5\"x 10\" INCH",
  "7.5\"x 10\" INCHES",
  "7.5\"x 10\" Inch",
  "7.5\"x 10\" Inches",
  "7.5\"X 10\" inch",
  "7.5\"X 10\" inches",
  "7.5\"X 10\" INCH",
  "7.5\"X 10\" INCHES",
  "7.5\"X 10\" Inch",
  "7.5\"X 10.5\" Inches",
  "7.5\"x 10\"",
  "7.5\"X 10\"",

  "10\" Diameter",
]

VOLUME_FORMATS_EXAMPLES = [
  "12 oz",
  "12 OZ",
  "12 OZ.",
  "12 oz.",
  "12.oz",
  "12.OZ",
  "12oz",
  "12OZ",
  "12.5 oz",
  "12.5 OZ",
  "12.5 OZ.",
  "12.5 oz.",
  "12.5.oz",
  "12.5.OZ",
  "12.5oz",
  "12.5OZ",
]

PRODUCT_VALUE_KEYWORDS = [
  "Biodegradable", "Compostable", "Recycled", "Eco-friendly", "Sustainable", "Green", "Environmentally friendly"
]

SIZE_REGEX = r"(\d+(\.\d+)?\s?\"\s?(x\s?\d+(\.\d+)?\s?\")?\s?(inch(es)?|INCH(ES)?|Inch(es)?|Diameter)?)"

DIMENSION_REGEX = r"(\d+(\.\d+)?\"\s?[xX]\s?\d+(\.\d+)?\"(?:\s?(inch(es)?|INCH(ES)?|Inch(es)?)?)?)|(\d+(\.\d+)?\"\s?(inch(es)?|INCH(ES)?|Inch(es)?)?)"

MATERIAL_REGEX = r"(\b(bamboo pulp|bamboo fiber|sugarcane pulp)\b)"

VOLUME_REGEX = r"\b(\d+\.?\d*\s?\.?oz\.?)\b"

PLY_REGEX = r"\b([1-9]\d*)\s*-?\s*ply\b"

SIZE_REGEX_PATTERNS = {
  "inches": r"\b\d+(\.\d+)?\s*(inches|inch|\"|“|”)\b",
  "other_units": r"\b\d+(\.\d+)?\s*(cm|centimeters?|meters?|meter|m|feet|ft)\b",
  "dimensions": r"\b\d+(\.\d+)?\s*(x|by)\s*\d+(\.\d+)?(x|by)\s*\d+(\.\d+)?\b",
  "size_descriptors": r"\b(small|medium|large|extra[-\s]large)\b"
}

INPUT_PATH_PROCESSING = 'data/scraped_data/products.csv'
OUTPUT_PATH_PROCESSING = 'data/processed_data/processed_products.csv'
FINAL_OUTPUT_PATH_PROCESSING_CSV = 'data/final_data/naturezway_products.csv'
FINAL_OUTPUT_PATH_PROCESSING_XLSX = 'data/final_data/naturezway_products.xlsx'
COLLECTIONS_PATH = 'data/scraped_data/collections.csv'
