"""
At the command line, only need to run once to install the package via pip:
"""
import os
import time
from dotenv import load_dotenv

import google.generativeai as genai

import pandas as pd

# Get the api key
load_dotenv()
API_KEY = os.getenv("GCP_API_KEY")

genai.configure(api_key=API_KEY)

# Set up the model
generation_config = {
  "temperature": 0.9,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 2048,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.0-pro",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

prompt_parts = [
  "From the title or description of a product, please extract the name of the product",
  "title/description 16oz Empty Plastic Juice Bottles with Tamper Evident Caps",
  "product name Empty Juice Bottles",
  "title/description Empty Plastic Juice Bottles with Tamper Evident Caps",
  "product name Empty Juice Bottles",
  "title/description 16oz Empty Clear Plastic Juice Bottles with Tamper Evident Caps",
  "product name Empty Clear Juice Bottles",
  "title/description 128oz Empty Plastic Juice Bottles with Tamper Evident Caps",
  "product name Empty Juice Bottles",
  "title/description 32oz Disposable Pet Clear Plastic Smoothie Cups with Clear Flat Lids",
  "product name Smoothie Cups with Flat Lids",
  "title/description 38MM Ratchet Caps and Lids for Plastic Juice Bottles For HDPE and Clear Plastic Juice Bottles, Smoothie Bottles, Fresh Squeezed Juice Container (Blue, Green, Orange)",
  "product name Ratchet Caps and Lids",
  "title/description 16oz Disposable Pet Clear Plastic Smoothie Cups with Sip Through Lids",
  "product name Smoothie Cups with Sip Through Lids",
  "title/description 500pc Clear Plastic Straws Individually Wrapped 7.75\" BPA Free, Food Safe",
  "product name Plastic Straws",
  "title/description 12oz Plastic Black Wine Goblet",
  "product name Wine Goblet",
  "title/description 12oz Empty Clear PET Plastic Juice Bottles with Black Tamper Evident Caps - Reusable Clear Beverage Containers",
  "product name Empty Juice Bottles",
  "title/description Aluminum Square Tin Muffin Pan 3 inch - Disposable Aluminum Cupcake Pans - Strong, Durable, Reusable, Recyclable - Muffin Tin Great for Baking Cupcakes, Muffins, Small Pies, Loafs (3 x 3)",
  "product name Aluminum Square Pans",
  "title/description Aluminum Pan Disposable Round Plastic Dome Lid (6inch, 7inch, 8inch, 9inch)",
  "product name Aluminum Pan with Plastic Dome Lid",
  "title/description Disposable Round Aluminum Foil Take-Out Pans",
  "product name Round Aluminum Foil Take-Out Pans",
  "title/description Aluminum 12-Cup Muffin Pan - Disposable Aluminum Cupcake Pans - Reusable, Recyclable - Muffin Tin Great for Baking Cupcakes, Muffins, Small Pies",
  "product name Aluminum Muffin Pan",
  "title/description 7\" Round Aluminum Foil Take-Out Pans, Disposable Containers",
  "product name Round Aluminum Foil Take-Out Pans",
  "title/description Round Flat Aluminum Foil Board Lids - Laminated (7inch, 8inch, 9inch)",
  "product name Round Flat Aluminum Foil Board Lids",
  "title/description Disposable 21\" x 13\" Full Size Deep Aluminum Foil Roasting and Steam Pans",
  "product name Deep Aluminum Foil Roasting and Steam Pans",
  "title/description Aluminum 6-Cup Muffin Pan - Disposable Aluminum Cupcake Pans - Reusable, Recyclable - Muffin Tin Great for Baking Cupcakes, Muffins, Small Pies",
  "product name Aluminum Muffin Pan",
  "title/description 9 x 13 Disposable Aluminum Steam Table Deep Pans, Half Size Foil Tin - Baker's Choice by EcoQuality",
  "product name Aluminum Steam Table Deep Pans",
  "title/description 9 x 13 Disposable Aluminum Steam Table Shallow Pans, Half Size Foil Tin - Baker's Choice by EcoQuality",
  "product name Aluminum Steam Table Shallow Pans",
  "title/description Yi Pin Chinese Hot Sauce Take Out Delivery Packets 8 Grams Per Packet No MSG Gluten Free",
  "product name Yi Pin Chinese Hot Sauce Take Out Delivery Packets",
  "title/description Clear Portion Plastic Cup with Hinged Lid Leak Proof Disposable Container",
  "product name Clear Portion Plastic Cup with Hinged Lid Leak Proof",
  "title/description 4oz Compostable Souffle Portion Cup with Lid, Disposable Biodegradable Tasting Sample Cups, Sauce Ramekin Cup , Condiment Cup, Jello Shot Cups",
  "product name Souffle Portion Cup with Lid",
  "title/description Yi Pin Chinese Duck Sauce Take Out Delivery Packets 8 Grams Per Packet No MSG Gluten Free",
  "product name Yi Pin Chinese Duck Sauce Take Out Delivery Packets",
  "title/description Yi Pin Chinese Soy Sauce Take Out Delivery Packets 8 Grams Per Packet No MSG Gluten Free",
  "product name Yi Pin Chinese Soy Sauce Take Out Delivery Packets",
  "title/description #8 Kraft Microwavable Folded Paper Take-Out Container 45oz",
  "product name Kraft Folded Paper Take-Out Container",
  "title/description Kraft Microwavable Folded Paper Take-Out Containers BIO BOX",
  "product name Kraft Folded Paper Take-Out Container BIO BOX",
  "title/description Kraft Paper Gift Bags with Twine Handles Brown Shopping Bags, Retail, Reusable, Party, Grocery Bags, Eco Friendly, Recyclable",
  "product name Kraft Paper Gift Bags",
  "title/description 1.5L X-Large Compostable Container Natural Sugarcane Sushi Trays with Lids",
  "product name Sushi Trays with Lids",
  "title/description 10x5x13 Medium Kraft Paper Gift Bags with Twine Handles Brown Shopping Bags, Retail, Reusable, Party, Grocery Bags, Eco Friendly, Recyclable",
  "product name Kraft Paper Gift Bags",
  "title/description 13\"x7\"x17\" Large Kraft Paper Gift Bags with Twine Handles Brown Shopping Bags, Retail, Reusable, Party, Grocery Bags, Eco Friendly, Recyclable",
  "product name Kraft Paper Gift Bags",
  "title/description Compostable Souffle Portion Cup, Disposable Biodegradable Tasting Sample Cups, Sauce Ramekin Cup , Condiment Cup, Jello Shot Cups",
  "product name Souffle Portion Cup",
  "title/description Non Woven Reusable Black T-Shirt Shopping Bags Large",
  "product name Reusable Shopping Bags",
  "title/description White Compostable Portion Cups with Lids, Biodegradable, Perfect for Disposable Sample Cups, TakeOut, Souffle, Salad Dressing, Condiments, Jello",
  "product name Portion Cups with Lids",
  "title/description 4oz White Compostable Portion Cups, Biodegradable, Perfect for Disposable Sample Cups, TakeOut, Souffle, Salad Dressing, Condiments, Jello",
  "product name Portion Cups",
  "title/description Allergen-Free Bakery Spatula, 10″ x 1-3/8″ Blade",
  "product name Bakery Spatula",
  "title/description Bakery Spatula, Polypropylene Handle Blade.",
  "product name Bakery Spatula",
  "title/description 16\" Round White Lace Paper Doilies, Disposable Paper Placemats for Wedding, Birthday, Cakes, Desserts, Tableware Food Decoration, Grease Proof 500PCS",
  "product name Round Lace Paper Doilies",
  "title/description Low Fold Dispenser Napkins 1-Ply Dispenser Napkin Refill",
  "product name Low Fold Dispenser Napkins",
  "title/description Straws Extra Wide, Bubble Tea Drinking Straws for Smoothies, Milkshakes, Slushies, Party Straws - Assorted Colors, Disposable Straws",
  "product name Extra Wide Straws",
  "title/description 3 - PLY 3 - PLY Black Disposable Face Masks with Soft Ear Loops, Non Medical / Non Surgical Masks - 50/Case",
  "product name Black Disposable Face Masks with Soft Ear Loops",
  "title/description 500pc Clear Plastic Straws Individually Wrapped 7.75\" BPA Free, Food Safe",
  "product name Clear Plastic Straws",
  "title/description Plastic Champagne Flutes 5 oz - Disposable Clear Glass Like Flutes - Champagne Glasses BPA Free - Weddings, Parties, Cocktail, Mimosas, Wine, Sodas",
  "product name Plastic Champagne Flutes",
  "title/description 18\" x 18\" White Corrugated Design Cardboard Perfect Pizza Recyclable Boxes",
  "product name Pizza Boxes",
  "title/description 12oz Pink Gold Rim Plastic Wine Goblets",
  "product name Plastic Wine Goblets",
  "title/description Elegant Cloth-Like Disposable Paper Dinner Napkins Gold Border",
  "product name Paper Dinner Napkins",
  "title/description Crystal Clear Plastic Beverage Pitcher - Break Resistant Beverage Carafe",
  "product name Plastic Beverage Pitcher",
  "title/description 3 Tier Coffee Cup Dispenser, Cup & Lid Organizer, 12 5/16\"L x 12 3/4\"W x 13 1/8\"H, Plastic, Black",
  "product name Coffee Cup Dispenser",
  "title/description 14 QT Stainless Steel Beverage Dispenser Punch Bowl with handles for Events and Parties",
  "product name Stainless Steel Beverage Dispenser",
  "title/description 24 QT High Capacity Bucket Beverage Dispenser for Events and Parties",
  "product name Bucket Beverage Dispenser",
  "title/description Silver Black Stainless Steel Slim Beverage Dispenser",
  "product name Stainless Steel Slim Beverage Dispenser",
  "title/description 12 QT Black Plastic Beverage Dispenser",
  "product name Plastic Beverage Dispenser",
  "title/description Clear Acrylic Double Wall Wine Bottle Cooler Perfect for Wine & Champagne",
  "product name Acrylic Wine Bottle Cooler",
  "title/description 60oz Stainless Steel Double Wall Wine Bottle Cooler Perfect for Wine & Champagne",
  "product name Stainless Steel Wine Bottle Cooler",
  "title/description Marble Wine Bottle Cooler Wine Chiller Bucket  Perfect for Wine & Champagne Holds a 750 ML Bottle",
  "product name Marble Wine Bottle Cooler",
  "title/description 34oz Square Clear Plastic Pitcher with White Lid",
  "product name Square Plastic Pitcher with Lid",
  "title/description 96oz Portable Box of Joe Disposable Coffee Dispenser for Insulated Hot Cold Drinks To Go",
  "product name Portable Box of Joe Disposable Coffee Dispenser",
  "title/description 4 Cup Drink Carrier Tray Biodegradable Pulp Fiber - Recycled, Disposable Take-Out Container Carrier for Drinks",
  "product name Cup Drink Carrier Tray",
  "title/description Poland Natural Spring Water in Plastic Bottle 40 Bottles/Case 16.9oz Each Bottle",
  "product name Poland Natural Spring Water",
  "title/description Disposable Kraft 2 or 4 Cup Drink Carrier with Handles, Paperboard Cup Holder",
  "product name Kraft Cup Drink Carrier with Handles",
  "title/description Bar Caddy with 6 Compartments, Plastic Bar Organizer, Heavy Duty Refillable Bar Organizer, Barware Caddy, Napkin Dispenser, Straw Organizer",
  "product name Bar Caddy with 6 Compartments",
  "title/description Netilat Yadayim Wash Cup Acrylic with Black Handle",
  "product name Netilat Yadayim Wash Cup",
  "title/description Netilat Yadayim Wash Cup Acrylic with Clear Handle",
  "product name Netilat Yadayim Wash Cup",
  "title/description Maintain 6 Feet Distance Sign - Removable, Weather Proof, Office Stickers, Safety Office Stickers, Vehicle Stickers, Decal for Car, School, Business 6 Feet Distance Sign",
  "product name Maintain 6 Feet Distance Sign",
  "title/description Face Mask Required Sticker Sign - Removable, Weather Proof, Office Stickers, Safety Office Stickers, Vehicle Stickers, Decal for Car, School or Business",
  "product name Face Mask Required Sticker Sign",
  "title/description 9\" x 3\" Black Rinse Plastic Sign - Removable, Weather Proof, Office Stickers, Required Safety Bathroom Kitchen Sign",
  "product name Rinse Plastic Sign",
  "title/description 9\" x 3\" Black Sanitize Plastic Sign - Removable, Weather Proof, Office Stickers, Required Safety Bathroom Kitchen Sign",
  "product name Sanitize Plastic Sign",
  "title/description MG15 White Butcher Food Paper Roll 15\" x 1000\"",
  "product name MG15 Butcher Food Paper Roll",
  "title/description Non Woven Reusable Green T-Shirt Shopping Bags Large",
  "product name Reusable Shopping Bags",
  "title/description Non Woven Reusable Thank You T-Shirt Shopping Bags Large",
  "product name Reusable Shopping Bags",
  "title/description MG15 Kraft Peach Butcher Food Paper Roll 15\" x 1000\"",
  "product name MG15 Kraft Butcher Food Paper Roll",
  "title/description MG30 White Butcher Food Paper Roll 30\"x 1000\"",
  "product name MG30 Butcher Food Paper Roll",
  "title/description MG18 White Butcher Food Paper Roll 18\" x 1000\"",
  "product name MG18 Butcher Food Paper Roll",
  "title/description Clear Reclosable Zip Poly Plastic Bags - Clear Resealable Storage Ziplock Bags - Great for Envelops, Bakery, Candy, Cookies and Post Cards",
  "product name Zip Poly Plastic Bags",
  "title/description Disposable 7\" x 5\" Resealable Grip\\'n Zip Plastic Sandwich Bags, Clear Kosher Zip Lock Lunch Bags",
  "product name Zip Plastic Sandwich Bags",
  "title/description 10x5x13 Medium Kraft Paper Gift Bags with Twine Handles Brown Shopping Bags, Retail, Reusable, Party, Grocery Bags, Eco Friendly, Recyclable",
  "product name Kraft Paper Gift Bags",
  "title/description Brown Kraft Bakery Bag with Clear Window 8.7 x 4.7 inches for Cookies, Pastries, Sandwich, Nuts - Grease Resistant",
  "product name Kraft Bakery Bag",
  "title/description 32oz Compostable Heavy Duty Disposable Bowls with Dome Lids, Ecofriendly, Bagasse Unbleached Bamboo, Biodegradable, Tree Free, Heat & Liquid Resistant Bowl",
  "product name Heavy Duty Disposable Bowls with Dome Lids",
  "title/description Bounty Kitchen Roll Paper Towels, 2-Ply, White, 48 Sheets/Single Plus Roll, 12 Rolls/Pack",
  "product name Kitchen Roll Paper Towels",
  "title/description 24oz Sugarcane Fiber Bowl with Plastic Lid Compostable Disposable Oblong Food Prep Storage",
  "product name Sugarcane Fiber Bowl with Plastic Lid",
  "title/description 2oz Clear Leak Proof Plastic Condiment Souffle Containers with Lids, Disposable - Perfect for Sauces, Samples, Slime, Jello Shots, Food Storage",
  "product name Souffle Containers with Lids",
  "title/description Disposable 21\" x 13\" Full Size Deep Aluminum Foil Roasting and Steam Pans",
  "product name Deep Aluminum Foil Roasting and Steam Pans",
  "title/description 29oz 2 Compartment Sugarcane Fiber Bowl with Sugarcane Lid Compostable Disposable Oblong Food Prep Storage",
  "product name Sugarcane Fiber Bowl with Sugarcane Lid",
  "title/description 32oz Twist Top Storage Deli Containers BPA-Free, Reusable Airtight Plastic Food Storage Leak Proof Canisters",
  "product name Twist Top Storage Deli Containers",
  "title/description 8oz Twist Top Plastic Storage Deli Containers BPA-Free, Reusable Airtight",
  "product name Twist Top Plastic Storage Deli Containers",
  "title/description 40oz Compostable Heavy Duty Disposable Bowls, Eco Friendly, Natural Bagasse Unbleached Bamboo, Biodegradable, Tree Free, Heat & Liquid Resistant Bowl",
  "product name Heavy Duty Disposable Bowls",
  "title/description 32oz Crystal Clear Plastic Disposable Salad Bowls with Lids To-Go with Lids Meal Prep Container",
  "product name Plastic Disposable Salad Bowls with Lids",
  "title/description EcoQuality Disposable Food Preparation Poly Gloves - One Size Fits All BPA FREE, Food Grade PE Disposable Gloves Latex & Powder Free",
  "product name Disposable Poly Gloves",
  "title/description Plastic Champagne Flutes 5 oz - Disposable Clear Glass Like Flutes - Champagne Glasses BPA Free - Weddings, Parties, Cocktail, Mimosas, Wine, Sodas",
  "product name Plastic Champagne Flutes",
  "title/description 12oz Stemless Plastic Goblets Blue Gold Rim",
  "product name Stemless Plastic Goblets",
  "title/description Disposable Signature White Paper Chef Hat",
  "product name Disposable Signature Paper Chef Hat",
  "title/description 5.5oz Disposable Silver Kiddush Cups and Saucer for Seder Table",
  "product name Disposable Silver Kiddush Cups and Saucer",
  "title/description EcoQuality Fancy Stemless Clear Disposable Plastic Champagne Flute Glass 9oz",
  "product name Stemless Disposable Plastic Champagne Flute Glass",
  "title/description 2 PLY Paper Towel Roll White Strong and Absorbent by EcoQuality",
  "product name Paper Towel Roll",
  "title/description Chafing Wire Buffet Rack - Stand Chrome Frame for Full Size Serving Pans, Full Size Chafing Dish Stand, Food Warmer for Catering, Events, Weddings, Parties, Birthdays",
  "product name Chafing Wire Buffet Rack",
  "title/description Popcorn Kettle Cleaning Kit",
  "product name Popcorn Kettle Cleaning Kit",
  "title/description Commercial Ultra Bleach Liquid Germicidal Disinfects Sanitizes Deodorizes, 1 Gallon, For Hospitals, Commercial Kitchens, Restaurants, Household, Nursing Homes",
  "product name Ultra Bleach Liquid Germicidal",
  "title/description Commercial Green Dish Soap Detergent Pot & Pan Professional Kitchen , 1Gallon, For Commercial Kitchens, Hotels, Restaurants, Household, Janitorial",
  "product name Green Dish Detergent",
  "title/description 1 Gallon - Liquid Hand Soap Refill, Pink Color, Floral Scent Hand Wash",
  "product name Liquid Hand Soap Refill",
  "title/description 1 Gallon (128 oz) Clear Plastic Bucket with Lid and Handle, Ice Cream Tub with Lids - Food Grade Freezer and Microwave Safe, BPA Free",
  "product name Plastic Bucket with Lid and Handle",
  "title/description Natural Kraft Hardwound Paper Towel 600 Feet per Roll, Great for Restaurants, Offices, Bars, Industrial - Recyclable Paper Towels",
  "product name Kraft Hardwound Paper Towel",
  "title/description 2 PLY Paper Towel Roll White Strong and Absorbent by EcoQuality",
  "product name Paper Towel Roll",
  "title/description Purell Advanced Hand Sanitizer Refreshing Gel, 8 oz with Pump Dispenser",
  "product name Hand Sanitizer",
  "title/description X Large Black Nitrile Exam Gloves, Disposable, Latex Rubber Free, Powder Free, Non Sterile, Food Safe, 4 Mil",
  "product name Nitrile Exam Gloves",
  "title/description Large Black Nitrile Exam Gloves, Disposable, Latex Rubber Free, Powder Free, Non Sterile, Food Safe, 4 Mil",
  "product name Nitrile Exam Gloves",
  "title/description Commercial Ultra Bleach Liquid Germicidal Disinfects Sanitizes Deodorizes, 1 Gallon, For Hospitals, Commercial Kitchens, Restaurants, Household, Nursing Homes",
  "product name Ultra Bleach Liquid Germicidal",
  "title/description 96oz Portable Box of Joe Disposable Coffee Dispenser for Insulated Hot Cold Drinks To Go",
  "product name Portable Box of Joe Disposable Coffee Dispenser",
  "title/description Disposable Travel Black Dome and White Dome Lids for Paper Hot Cups (10oz, 12oz, 16oz, 20oz)",
  "product name Disposable Travel Dome Lids",
  "title/description Disposable Paper Hot Cups - Double Wall Paper Coffee Cups (8oz, 12oz, 16oz)",
  "product name Disposable Paper Hot Cups",
  "title/description Design Disposable Paper Coffee Cups with White Flat Lids",
  "product name Disposable Paper Coffee Cups with Flat Lids",
  "title/description 20Lb Jumbo White Kraft Heavy Duty Grocery Tall Paper Lunch Bags",
  "product name Kraft Lunch Bags",
  "title/description 2LB White Kraft Paper Bags, Bakery Bags, Candy Bags, Party Favor Bags, Grocery Bags, Craft Bags #2 Small Lunch Paper Bags",
  "product name Kraft Paper Bags",
  "title/description 16LB White Kraft Paper Bags, Bakery Bags, Supermarket Bags, Gift Bags, Grocery Bags, Craft Bags #16 Heavy Duty Tall Paper Bags",
  "product name Kraft Paper Bags",
  "title/description 8LB White Kraft Paper Bags, Bakery Bags, Candy Bags, Party Favor Bags, Grocery Sandwich Bags, Craft Bags #8 Large Lunch Paper Bags",
  "product name Kraft Paper Bags",
  "title/description Compostable Rectangular Food Containers with Lids, Ecofriendly Take- Out, Made With Bagasse",
  "product name Rectangular Food Containers with Lids",
  "title/description Compostable Clamshell Take Out Food Container 6x9x3",
  "product name Clamshell Take Out Food Container",
  "title/description Compostable Eco Friendly Cutlery 6.5 inch - CPLA Heat Resistant Disposable Utensils Durable Cornstarch Bio Based Biodegradable (Forks, Spoons, Knives)",
  "product name Compostable Cutlery",
  "title/description Compostable Biodegradable Take Out Food Containers with Clamshell Hinged Lid Microwaveable, Disposable Takeout Box to Carry Meals Togo [6x6, 9x9, 9x6]",
  "product name Take Out Food Containers with Clamshell Hinged Lid",
  "title/description Disposable Kraft Paper Food Soup Cup with Paper Vented Lid",
  "product name Kraft Paper Food Soup Cup with Paper Lid",
  "title/description 34oz Compostable Rectangular Food Containers with Lids, Ecofriendly Take- Out, Made With Bagasse",
  "product name Rectangular Food Containers with Lids",
  "title/description Eco-Friendly 3 Compartment  Hinged Clamshell Heavy-Duty Disposable Containers",
  "product name 3 Compartment Hinged Clamshell",
  "title/description Compostable Heavy Duty Disposable Bowls with Lids, Ecofriendly, Bagasse Unbleached Bamboo, Biodegradable, Tree Free, Heat & Liquid Resistant Bowl",
  "product name Heavy Duty Disposable Bowls with Lids",
  "title/description Disposable Kraft Hot Cup Sleeves Paper Cup Jackets - Corrugated Coffee Cup Sleeves - Recyclable, Compostable - Fits most 10oz, 12oz, 16oz, 20oz",
  "product name Kraft Hot Cup Sleeves",
  "title/description #8 Kraft Microwavable Folded Paper Take-Out Container 45oz",
  "product name Kraft Folded Paper Take-Out Container",
  "title/description 8 Quart Stainless Steel Full-Size Folding Stand Heavyweight Chafer",
  "product name Folding Stand Chafer",
  "title/description 8 Quart Deluxe Full Size Rectangular Gold Accent Chafer Roll Top Cover Heavyweight",
  "product name Rectangular Chafer",
  "title/description 8 Quart Oval Stainless Steel Chafer, Roll-Top, Formal and Casual Events Food Pan Heavyweight",
  "product name Oval Chafer",
  "title/description 6 Quart Round Stainless Steel Chafer, Roll-Top, Formal and Casual Events Food Pan Heavyweight",
  "product name Round Chafer",
  "title/description 8 Quart Full Size Stainless Steel Chafer, Roll-Top, Formal and Casual Events Food Pan Heavyweight",
  "product name Full Size Chafer",
  "title/description EcoQuality Polished 8 Quart Full-size Chafer, Roll-top, Stainless Steel, Gold Accent, Extra Heavyweight",
  "product name Full size Chafer",
  "title/description Wooden Kitchen Cooking Spoon, Solid Wood Serving Spoons for Stirring, Mixing, Non Stick Kitchen Utensil, Tableware, Scoop Ladle for Stews, Soups, Pasta, Salad, Sauce",
  "product name Wooden Kitchen Spoon",
  "title/description Chafing Wire Buffet Rack - Stand Chrome Frame for Full Size Serving Pans, Full Size Chafing Dish Stand, Food Warmer for Catering, Events, Weddings, Parties, Birthdays",
  "product name Chafing Wire Buffet Rack",
  "title/description Wooden Kitchen Utensil Set, Wooden Spoon & Spatula, Non Stick Cookware, Kitchen Cooking Tools, Kitchenware, Restaurant and Home with Hang Holes",
  "product name Wooden Kitchen Utensil Set",
  "title/description Methanol Blue Gel Chafing Fuel Cans 7 oz - Burns 2.5-Hours - Cooking Fuel - Canned Heat",
  "product name Methanol Blue",
  "title/description Soya Bean Salad Oil 35LB Healthy Brand, General Purpose Soy Bean Vegetable Oil, No trans fat, Use for Pan Frying, Salad dressing, Sauces and Baking",
  "product name Soya Bean Salad Oil",
  "title/description 10\" Round Compostable Natural Sugarcane Plates",
  "product name Round Compostable Natural Sugarcane Plates",
  "title/description Compostable Cutlery Kit Ecofriendly Fork, Spoon, Knife, Napkin 6.5 in - CPLA Heat Resistant Disposable Durable Utensils, Biodegradable Plastic Cutlery",
  "product name Compostable Cutlery Kit",
  "title/description White Heavy Duty Disposable Paper Plates (9inch)",
  "product name Heavy Duty Disposable Paper Plates",
  "title/description Disposable Kraft 6-Inch Paper Plates Uncoated Small, Everyday Disposable Brown Paper Plates 6\" Paper Plate Bulk Pizza Party Plates",
  "product name Disposable Kraft Paper Plates",
  "title/description EcoQuality Disposable Kraft 9-Inch Paper Plates Uncoated Large, Everyday Disposable Brown Paper Plates 9\" Paper Plate Bulk Pizza Party Plates",
  "product name Disposable Kraft Paper Plates",
  "title/description Super Bright 3 LED Module with Remote - 5050 Injection Module with 12V AC Power Adapter",
  "product name 3 LED Module with Remote",
  "title/description Plastic Knives Gold Infinity Flatware Collection",
  "product name Plastic Knives Flatware Collection",
  "title/description Plastic Black Infinity Flatware Collection",
  "product name Plastic Flatware Collection",
  "title/description Disposable Plastic Wrapped White Heavy Duty Cutlery Kit 4 in 1 - Fork/Spoon/Knife/Napkin",
  "product name Disposable Plastic Cutlery Kit",
  "title/description Plastic Gold Infinity Flatware Collection",
  "product name Plastic Flatware Collection",
  "title/description 10oz Disposable Pet Clear Plastic Smoothie Cups",
  "product name Disposable Plastic Smoothie Cups",
  "title/description 14oz Disposable Pet Clear Plastic Smoothie Cups",
  "product name Disposable Plastic Smoothie Cups",
  "title/description Round Plastic Trash Can Dolly 18 inches - Transport for Trash Cans",
  "product name Round Plastic Trash Can Dolly",
  "title/description Heavy-Duty Round Trash Can 10 Gallon Grey - Plastic Garbage Can",
  "product name Heavy-Duty Round Trash Can",
  "title/description 28 Quart Black Plastic Rectangular Trash Can - Trash Can for Offices, Home, Restaurant",
  "product name Plastic Rectangular Trash Can",
  "title/description 28 Quart Blue Polyethylene Recycling Bin Wastebasket for Offices, Home, Restaurant",
  "product name Polyethylene Recycling Bin Wastebasket",
  "title/description 41 qt Rectangle Waste Basket - Plastic, Black for Offices, Home, Restaurants",
  "product name Rectangle Waste Basket",
  "title/description Black Strong Wastebasket Receptacle Can Liner Heavy Duty Garbage Trash Bags (13, 30, 39, 46, 50, 58 Gallon)",
  "product name Heavy Duty Garbage Trash Bags",
  "title/description Plastic Trash Bags - White Tall Kitchen Garbage Bags (13 Gallon)",
  "product name Plastic Trash Bags",
  "title/description Plastic Strong Blue Recycling Trash Bags Wastebasket Receptacle Can Liner Large Heavy Duty Garbage Bags (46 Gallon)",
  "product name Plastic Trash Bags",
  "title/description Large Heavy Duty Clear Trash Bags 35x55 inch",
  "product name Heavy Duty Trash Bags",
  "title/description TZ-015 Disposable Black Sakura Design Take Out Sushi Trays with Clear Lids 8 1/2\" X 5 1/4\" X 5/8\"",
  "product name Disposable Sushi Trays with Clear Lids",
  "title/description TZ-010 Disposable Black Sakura Design Take Out Sushi Trays with Clear Lids 7 3/8\" X 5 1/8\" X 7/8\"",
  "product name Disposable Sushi Trays with Clear Lids",
  "title/description TZ-010 Disposable Black Sakura Design Take Out Sushi Trays 7 3/8\" X 5 1/8\" X 7/8\"",
  "product name Disposable Take Out Sushi Trays",
  "title/description TZ-001 Disposable Black Sakura Design Take Out Sushi Trays 8 3/4\" X 3 3/4\" X 7/8\"",
  "product name Disposable Take Out Sushi Trays",
  "title/description TZ-0.6 Disposable Clear Recycled PET Lids for Black Sakura Trays  6 3/8\" X 3 1/2\" X 1 1/8\"",
  "product name Disposable Lids",
  "title/description TZ-0.6 Disposable Black Sakura Design Take Out Sushi Trays 6 3/8\" X 3 1/2\" X 3/4\"",
  "product name Disposable Take Out Sushi Trays",
  "title/description 12 Inch Bamboo Skewers - Biodegradable, Sturdy, Eco-Friendly, Reusable, Great for BBQ, Grilling and more!",
  "product name Bamboo Skewers",
  "title/description Snow Cone Spoon Straws Red 200 Per Pack",
  "product name Snow Cone Spoon Straws",
  "title/description Unwrapped Disposable Paper Drinking Straws White 7.75 Inches - Compostable, Biodegradable, Earth Friendly Straws, Premium Unwrapped Paper Straws",
  "product name Disposable Paper Drinking Straws",
  "title/description Multi Color Cocktail Umbrella Picks - Elegant Drink Umbrellas, Parasol Cocktail Picks, Toothpicks, Bar Supplies, Party Supplies, Cupcake Toppers by EcoQuality (4 Inches)",
  "product name Multi Color Cocktail Umbrella Picks",
  "title/description Compostable Plastic Stirrer, Bio Degradable, Eco Friendly, Sip Stirrer, Bar Stirrer, Sip Straw, For Coffee, Cocktail, Latte and Tea - Red",
  "product name Compostable Plastic Stirrer",
  "title/description Wooden Coffee Stirrer Sticks 7.5 inch",
  "product name Wooden Coffee Stirrer Sticks",
  "title/description Wire Shelf, Epoxy-Coated, Width 14''",
  "product name Wire Shelf",
  "title/description Wire Shelf, Epoxy-Coated, Width 18''",
  "product name Wire Shelf",
  "title/description Chrome Plated Wire Shelf 4 Shelf Adjustable - Chrome Finished Heavy Duty Adjustable Shelf, Metal Organizers (Chrome, 14Wx24L)",
  "product name Chrome Plated Wire Shelf",
  "title/description 2oz Leak Proof Black Plastic Condiment Souffle Containers with Lids, Disposable - Perfect for Sauces, Samples, Slime, Jello Shots, Food Storage",
  "product name Plastic Condiment Souffle Containers with Lids",
  "title/description 4oz Clear Leak Proof Plastic Condiment Souffle Disposable Containers with Hinged Lids, Perfect for Sauces, Samples, Slime, Jello Shots, Food Storage",
  "product name Plastic Condiment Souffle Containers with Lids",
  "title/description 33oz 3 Compartment Rectangular Meal Prep Containers with Lids Black, Food Storage Containers | BPA Free Lunch Boxes Microwave/Dishwasher/Freezer Safe",
  "product name 3 Compartment Rectangular Meal Prep Containers with Lids",
  "title/description Bamboo Wood Knot Cocktail Skewer Picks - 3.5 Inches Great for Appetizers, Parties, Samplers, Hors' D'oeuvre, Snacks, Cheese, Biodegradable",
  "product name Bamboo Wood Knot Cocktail Skewer Picks",
  "title/description 24 Oz Clear Plastic Condiment Squeeze Bottles, Squirt Bottle for Sauces, Dressing - BPA Free, Dishwasher Safe",
  "product name Plastic Condiment Squeeze Bottles",
  "title/description Aluminum Disposable Durable Oval Roaster Pan Turkey Pan",
  "product name Aluminum Oval Roaster Pan",
  "title/description Wooden Craft Sticks Great for Arts and Crafts",
  "product name Wooden Craft Sticks",
  "title/description Multi Colored Wooden Craft Sticks - Great for Arts and Crafts, Natural Wooden Treat Sticks, Colored Popsicles Sticks, Ice Cream Sticks Ideal for Kids, Teachers and Students",
  "product name Multi Colored Wooden Craft Sticks",
  "title/description #19 Red Rubber Bands 1250pc Per Box (3-1/2\" x 1/16\" )",
  "product name Rubber Bands",
  "title/description #12 Red Rubber Bands 2500pc Per Box (1-3/4\" x 1/16\")",
  "product name Rubber Bands",
  "title/description Clear Packaging Shipping Tape 2\" x 110 Yards",
  "product name Packaging Shipping Tape",
  "title/description Clear Plastic Stretch Film Wrap 18\" x 1500′ 80 Gauge Loads Pallets Up To 2500LB",
  "product name Plastic Stretch Film Wrap",
  "title/description 5 Gallon Shelf Ingredient Bin with Lid, 80-Cup, NFS Listed",
  "product name Shelf Ingredient Bin with Lid",
  "title/description 2 Gallon Shelf Ingredient Bin with Lid, 40-Cup, NFS Listed",
  "product name Shelf Ingredient Bin with Lid",
  "title/description Tamper-Resistant Clear Hinged Container with Flat Lid",
  "product name Hinged Container with Flat Lid",
  "title/description Paper Towel Dispenser, Center Pull",
  "product name Paper Towel Dispenser",
  "title/description Paper Towel Dispenser, Lever Handle",
  "product name Paper Towel Dispenser",
  "title/description Thermal Cash Register Rolls (1-3/4\" x 150 ft, 2-1/4\" x 50 ft, 3-1/8\" x 200 ft, 3-1/8\" x 220 ft, 3-1/8\" x 230 ft )",
  "product name Thermal Cash Register Rolls",
  "title/description Countertop Refrigerated Beverage Display,110-120V,230W,2.7A, Dual Curved Doors (White / Black)",
  "product name Countertop Refrigerated Beverage Display",
  "title/description 5 Ply Disposable Protective Face Masks, 3D Foldable Fitting Design with Stretchy Ear Loops - KN95",
  "product name Disposable Protective Face Masks",
  "title/description 3-PLY Protective Earloop Face Masks for Kids with 6 Colors Pink, Yellow, Green, Blue, White, Kids Cartoon All in One Box 50/Case",
  "product name Protective Earloop Kids Face Masks",
  "title/description Round Plastic Deli Food Storage Containers with Lids Translucent Clear (8oz, 16oz, 32oz)",
  "product name Round Plastic Food Containers with Lids",
  "title/description Small 1/10 Plastic White T-Shirt Bags, 8\" x 15\" Reusable Recyclable Shopping Bags Merchandise Bag",
  "product name Reusable Shooping Bags",
  "title/description Food Storage Bags Clear Plastic Produce Bags on a Roll",
  "product name Food Bags",
  "title/description 18\"x 24\" Food Storage Bags Clear Plastic Produce Bags on a Roll",
  "product name Food Bags",
  "title/description 24oz Disposable Pet Clear Plastic Smoothie Cups with Sip Through Lids",
  "product name Plastic Smoothie Cups with Sip Through Lids",
  "title/description Pizza Saver Stand - White Plastic Tabletop Pizza Tripod Stack, Disposable White Pizza Saver for Pizza Box, Catering Box, Takeout, Restaurant",
  "product name Pizza Saver Stand",
  "title/description 2 Door Pizza Warmer / Merchandiser. Size 12''& 18''",
  "product name 2 Door Pizza Warmer",
  "title/description 115mm Vented Lids for Paper Soup Containers Fits 12oz, 16oz , 26oz, 32oz (Kraft, White)",
  "product name Vented Lids",
  "title/description Waxed Deli Paper Sheets (Dry, Wet)",
  "product name Waxed Paper Sheets",
  "title/description 10Lb Kraft Brown Bakery Grocery Paper Bags #10 Large Packaging Paper Bags, Great for Lunch Bags, Small Snacks, Gift Bags, Merchandise, Party DIY Bags",
  "product name Kraft Paper Bags",
  "title/description 6Lb Kraft Brown Bakery Grocery Paper Bags #6 Medium Packaging Paper Bags, Great for Lunch Bags, Small Snacks, Gift Bags, Merchandise, Party DIY Bags",
  "product name Kraft Paper Bags",
  "title/description Manual Pallet Jack With Foot Pedal 5500LBS Capacity",
  "product name Manual Pallet Jack with Pedal",
  "title/description Clear Plastic Stretch Film Wrap 18\" x 1500′ 80 Gauge Loads Pallets Up To 2500LB",
  "product name Plastic Stretch Film Wrap",
  "title/description 5oz Miniware Round Plastic Cups With Dome Lids",
  "product name Miniware Round Plastic Cups with Dome Lids",
  "title/description 4oz Miniware Plastic Bowl with Flat Lid",
  "product name Miniware Plastic Bowl with Flat Lid",
  "title/description Hot Dog Roller Grill , Hot Dog Capacity 10, 20 & 30",
  "product name Hot Dog Roller Grill"
]

# Train the model with data
model.generate_content(prompt_parts)

# Get the new prompts from the products titles
products_df = pd.read_csv('data/gcp/ecoquality_titles.csv', keep_default_na=False, low_memory=False)

# Clean the titles
bad_titles = []
for index, row in products_df.iterrows():

    # Get the title
    title = row['title']

    # Wait 1 second to avoid the rate limit
    time.sleep(2)

    # Ask to the model to clean the title
    response = model.generate_content(f"From the title or description of a product, please extract the name of the product by removing the specs from it (volume, size, color, among others): \n title/description {title}")

    print(f"{index}. Title: {title}")

    # Save the clean title
    try:
        clean_title = response.text
        row['cleanTitle'] = clean_title
        print(f"Clean title: {clean_title}\n")
    except ValueError:
        bad_titles.append(title)
        row['cleanTitle'] =  title
        print(f"Not cleaned: {response} \n")
    except AttributeError:
        bad_titles.append(title)
        row['cleanTitle'] =  title
        print(f"Not cleaned: {response} \n")

# Save the updated dataframe
products_df.to_csv('data/gcp/ecoquality_titles_cleaned_v2.csv', index=False)

# Print the bad titles
print("Bad titles:")
for title in bad_titles:
    print(title)
