BASE_URL = "https://shop.sysco.com/"
BASE_LOGIN_URL = "https://shop.sysco.com/auth/login"

CATEGORIES =[
    ("fruitvegetables",1962),
    ("meatseafood", 2945),
    ("bakerybread", 1883),
    ("dairyeggs", 946),
    ("canneddry", 7508),
    ("frozenfoods", 776),
    ("beverages", 1522),
    ("suppliesequipment", 15467),
]

SUPPLIES_SUBCATEGORIES =[
   "apparelanduniforms",
   "catering",
   "dispensers",
   "disposables",
   "foodstorageandwraps",
   "furniture",
   "healthandpersonalcare",
   "janitorialandcleaning",
   "kitchenandcutlery",
   "othersupplies",
   "registerandpos",
   "restaurantequipment",
   "tabletopdiningandbar",
]


CATEGORY_BASE_URL = "https://shop.sysco.com/app/catalog?BUSINESS_CENTER_ID=syy_cust_tax_"
SUPPLIES_BASE_URL = "https://shop.sysco.com/app/catalog?BUSINESS_CENTER_ID=syy_cust_tax_suppliesequipment&ITEM_GROUP_ID=syy_cust_tax_"

TIMEOUT = 10

HEADERS = [
    'uniqueIdentifier',
    'url',
    'availableForSale',
    'title',
    'description',
    'metaTitle',
    'metaDescription',
    'vendor',
    'manufacturerName',
    'brand',
    'model',
    'price',
    'vendorCategory.0',
    'vendorCategory.1',
    'vendorCategory.2',
    'vendorCategory.3',
    'vendorCategory.4',
    'categories.0',
    'categories.1',
    'material',
    'color',
    'approvedBy',
    'totalInventory',
    'images.0',
    'images.1',
    'images.2',
    'images.3',
    'images.4',
    'images.5',
    'images.6',
    'images.7',
    'images.8',
    'manufacturerNumber',
    'upc',
    'sku',
    'specs.0.name','specs.0.value',
    'specs.1.name','specs.1.value',
    'specs.2.name','specs.2.value',
    'specs.3.name','specs.3.value',
    'specs.4.name','specs.4.value',
    'specs.5.name','specs.5.value',
    'specs.6.name','specs.6.value',
    'specs.7.name','specs.7.value',
    'specs.8.name','specs.8.value',
    'specs.9.name','specs.9.value',
    'specs.10.name','specs.10.value',
    'specs.11.name','specs.11.value',
    'specs.12.name','specs.12.value',
    'option.0.name','option.0.value',
    'option.1.name','option.1.value',
    'option.2.name','option.2.value',
    'productMinOrderCases',
    'productMinOrderPrice',
    'caseSize',
    'packSize',
    'productLength',
    'productWidth',
    'productHeight',
    'productWeight',
    'packageLength',
    'packageWidth',
    'packageHeight',
    'packageWeight',
    'shippingFrom',
    'shippingCost',
    'freeShipping',
    'certificationsAndStandards',
    'origin',
    'productValue.0',
    'productValue.1',
    'canCustomize',
    'ourCost',
    'despensingType',
    'packagingType',
    'productForm',
    'scent',
    'volumeML',
    'volumeOZ',
    'border',
    'design',
    'shape',
    'towelType',
    'weightGSM',
    'feerPerRoll',
    'numberOfRolls',
    'numerOfSheets',
    'ply',
    'fit',
    'pattern',
    'threadCount',
    'pocketDepth',
    'ingredients',
    'itemForm',
    'microwaveSafe',
    'thickness',
    'syscoPackSize',
    'syscoId',
]