"""ALL PRODUCTS PARAMETERS"""

HEADERS = [
    'uniqueIdentifier',
    'url',
    'availableForSale',
    'title',
    'description',
    'metaTitle',
    'metaDescription',
    'vendor',
    'manufacturerName',
    'brand',
    'model',
    'price',
    'vendorCategory.0',
    'vendorCategory.1',
    'vendorCategory.2',
    'vendorCategory.3',
    'categories.0',
    'categories.1',
    'material',
    'color',
    'approvedBy',
    'totalInventory',
    'images',
    'manufacturerNumber',
    'upc',
    'sku',
    'specifications',
    'options',
    'productMinOrderCases',
    'productMinOrderPrice',
    'caseSize',
    'packSize',
    'size',
    'stdSize',
    'productLength',
    'productWidth',
    'productHeight',
    'productWeight',
    'packageLength',
    'packageWidth',
    'packageHeight',
    'packageWeight',
    'shippingFrom',
    'shippingCost',
    'freeShipping',
    'certificationsAndStandards',
    'origin',
    'productValues',
    'canCustomize',
    'ourCost',
    'despensingType',
    'packagingType',
    'productForm',
    'scent',
    'volume',
    'border',
    'design',
    'shape',
    'towelType',
    'weightGSM',
    'feetPerRoll',
    'numberOfRolls',
    'numerOfSheets',
    'ply',
    'fit',
    'pattern',
    'threadCount',
    'pocketDepth',
    'ingredients',
    'itemForm',
    'microwaveSafe',
    'thickness',
]

PRODUCT_COLUMNS = [
    'id',
    'url',
    'title',
    'description',
    'brand',
    'type', # Need processing
    'price', # Need processing
    'stock', # Need processing
    'box_upc', # In upc
    'retail_upc', # In specs
    'unit_upc', # In specs
    'images', # Need processing
    'volume', # Need processing
    'ingredients',
    'product_values',
]
